export const inputFieldValues =  [
    {
        value:'name',
        name:'name',
        label:'Lugar',
        type:'text',
        error:'name',
        helperText:'name'
    },
    {
        value:'direction',
        name:'direction',
        label:'Dirección',
        type:'text',
        error:'direction',
        helperText:'direction'
    },
    {
        value:'address_details',
        name:'address_details',
        label:'Detalles',
        type:'text',
        error:'address_details',
        helperText:'address_details'
    },
    {
        value:'postal_code',
        name:'postal_code',
        label:'Código Postal',
        type:'number',
        error:'postal_code',
        helperText:'postal_code'
    },
    {
        value:'country',
        name:'country',
        label:'País',
        type:'text',
        error:'country',
        helperText:'country'
    },
    {
        value:'state',
        name:'state',
        label:'Provincia',
        type:'text',
        error:'state',
        helperText:'state'
    },
    {
        value:'city',
        name:'city',
        label:'Ciudad',
        type:'text',
        error:'city',
        helperText:'city'
    },
];